### ISSUE TITLE
Port GUI to GIO UI

### ISSUE THREAD

**Issue by scartill** [iegomez/lds#20]
To overcome IMGUI limitations. Will be collected in feat/gui-port branch

**Comment by scartill** [comment]
After some research, it looks like Fyne compiles under Windows via Mingw, Cygwin or similar, which is not known as superstable.

Also, GIO UI (https://eliasnaur.com/blog/immediate-mode-gui-programming) is natively crossplatform immediate GUI library.

If @iegomez doesn't mind, I propose to give it a try.

**Comment by iegomez** [comment]
Sure, sounds good! I'm actually wrapping up a Go project at work and moving to other languages for the upcoming one next week, so I thought it'd be nice to give GUI packages a try and keep doing some Go, but please feel free to start working on it if you want and I'll join later.

**Comment by iegomez** [comment]
Hey, @scartill!

Just wanted to say sorry because I haven't found the time to support your efforts. With the whole world situation, a tight schedule at work and trying to keep with maintenance for my mosquitto plugin project, there's just too little time. 

I'm really grateful for all your work pushing this package forward, so please, if you need a hand with anything, just let me know and I'll make sure to set aside some time to help.

Cheers!

**Comment by scartill** [comment]
Hi, @iegomez !

Thanks for encouraging! Indeen, situation is non-trivial at the least (and I'm into aviation, you know, which is kinda (un)dead), so I'm just trying to take advantage of my work being of impulse nature nowaday.

If you would have a spare minute, please take a closer look on #19, since it may be more complex than it looks (or not :)

Stay safe!

**Comment by scartill** [comment]
Closed by #21
