### ISSUE TITLE
Docker Env

### ISSUE THREAD

**Issue by wolftrax5** [iegomez/lds#6]
I was trying to run this on docker but not successful is there any way 
using a image of  golang:1.12
`docker run --rm -it -v "$PWD":/usr/src/lds -w /usr/src/lds golang:1.12`

then install the dependencies
`root@e16a31086b10: apt install build-essential xorg-dev libgl1 libgl1-mesa-dev libgl1-mesa-glx redis-server`

and run the "make" but the executable didn't work 

PD: Exelente Trabajo, Saludos desde Mexico.

**Comment by iegomez** [comment]
Hi! Thanks for the kind words!

I'm not entirely sure as things may have changed, but I believe it shouldn't work in the regular `Go` docker images as they are based on Alpine, whcih uses `musl libc` and which in turn doesn't play along with `Cgo`. The latter is needed because this project uses `imgui-go`, which is basically a wrapper of the `C` library `Dear imgui`.

I'd recommend basing in something different such as `debian-slim` and downloading Go there to build the program.
